// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TuitionsOnlineAdmin.DataStore.EntityFramework;

namespace TuitionsOnlineAdmin.DataStore.EntityFramework.Migrations
{
    [DbContext(typeof(TuitionsOnlineAdminDbContext))]
    [Migration("20210108073523_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("TuitionsOnlineAdmin.CoreBusiness.GraduateCourse", b =>
                {
                    b.Property<string>("GraduateCourseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("GraduateCourseName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GraduateCourseId");

                    b.ToTable("GraduateCourse");
                });
#pragma warning restore 612, 618
        }
    }
}
